--------------------------------------------------------
--  File created - Saturday-June-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRAINERS
--------------------------------------------------------

  CREATE TABLE "N01296956"."TRAINERS" 
   (	"TRAINER_ID" VARCHAR2(6 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"EXPERIENCE" VARCHAR2(200 BYTE), 
	"SALARY" NUMBER, 
	"PAYDATE" DATE, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER(10,0), 
	"SCHEDULE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "S19ITE5220ONAGURDEEP" ;
--------------------------------------------------------
--  DDL for Index TRAINERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "N01296956"."TRAINERS_PK" ON "N01296956"."TRAINERS" ("TRAINER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "S19ITE5220ONAGURDEEP" ;
--------------------------------------------------------
--  Constraints for Table TRAINERS
--------------------------------------------------------

  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("TRAINER_ID" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("PAYMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("PAYDATE" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" MODIFY ("SCHEDULE_DATE" NOT NULL ENABLE);
  ALTER TABLE "N01296956"."TRAINERS" ADD CONSTRAINT "TRAINERS_PK" PRIMARY KEY ("TRAINER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "S19ITE5220ONAGURDEEP"  ENABLE;
